### ISSUE TITLE
Can not use click event on the icon

### ISSUE THREAD

**Issue by manegame** [ABarnob/svelte-remixicon#4]
I would like to propose to forward mouse events so we can use markup like this;

`<RiSkipRightFill on:click={next} />`

I might make a PR for this when I have time

**Comment by aantusahaa** [comment]
This option was there in previous versions of this library, but it was removed in the latest version. 
The reason being the component will place in a `<svg>` tag, and these tags should not be click targets by default for accessibility. It is preferable to wrap these components in `<button>` tag and add relevant handlers there. In that way, even who are using your application with a screen reader or maybe just trying to navigate your application with keyboard only will get proper feedbacks. It was removed to discourage adding click handlers to non-interactive elements.

**Comment by aantusahaa** [comment]
A section has been added on the usage of events. [Usage example](https://github.com/aantusahaa/svelte-remixicon?tab=readme-ov-file#using-events)
Thanks!
