### ISSUE TITLE
Very slow performance when using Sveltekit & Vite

### ISSUE THREAD

**Issue by milansimek** [ABarnob/svelte-remixicon#5]
When using this package with Sveltekit & Vite, it significantly slows down the loading/reloading process to the point it's unusable. 

This is especially noticeable when debugging server code using breakpoints.

The reason seems to be that Vite optimizes each icon, even when only including a single icon in a component. This is probably because they're are all defined  in `index.js`.  

There must be a workaround to address this issue, although I'm not sure which one (yet) :)

**Comment by aantusahaa** [comment]
It seems the only option is to allow importing individual icons separately. 
I will work on this. Thanks for taking time to report the issue. :)

**Comment by milansimek** [comment]
@aantusahaa Yes I think that's the way indeed. This other library supports importing icons directly: https://github.com/shinokada/svelte-remix  

Maybe you can check the code and implement the same in yours :)

**Comment by aantusahaa** [comment]
@milansimek please update the package to the latest version `v2.1.0` and use direct imports of the components. [Usage example](https://github.com/aantusahaa/svelte-remixicon?tab=readme-ov-file#simple-usage)
Thanks again!
